test: &default

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  username: anuj_api1.skybulls.com
  password: 1365876690
  signature: A2WYR.9uwMxZhLsS6EJq3d0o3LSJA8m6GPeoM8ti1ssm7ttqkwyToc-Q
  app_id: APP-80W284485P519543T
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: anuj@skybulls.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
