require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GlucoseDataController do

  # This should return the minimal set of attributes required to create a valid
  # GlucoseDatum. As you add validations to GlucoseDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GlucoseDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all glucose_data as @glucose_data" do
      glucose_datum = GlucoseDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:glucose_data).should eq([glucose_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested glucose_datum as @glucose_datum" do
      glucose_datum = GlucoseDatum.create! valid_attributes
      get :show, {:id => glucose_datum.to_param}, valid_session
      assigns(:glucose_datum).should eq(glucose_datum)
    end
  end

  describe "GET new" do
    it "assigns a new glucose_datum as @glucose_datum" do
      get :new, {}, valid_session
      assigns(:glucose_datum).should be_a_new(GlucoseDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested glucose_datum as @glucose_datum" do
      glucose_datum = GlucoseDatum.create! valid_attributes
      get :edit, {:id => glucose_datum.to_param}, valid_session
      assigns(:glucose_datum).should eq(glucose_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GlucoseDatum" do
        expect {
          post :create, {:glucose_datum => valid_attributes}, valid_session
        }.to change(GlucoseDatum, :count).by(1)
      end

      it "assigns a newly created glucose_datum as @glucose_datum" do
        post :create, {:glucose_datum => valid_attributes}, valid_session
        assigns(:glucose_datum).should be_a(GlucoseDatum)
        assigns(:glucose_datum).should be_persisted
      end

      it "redirects to the created glucose_datum" do
        post :create, {:glucose_datum => valid_attributes}, valid_session
        response.should redirect_to(GlucoseDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved glucose_datum as @glucose_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        GlucoseDatum.any_instance.stub(:save).and_return(false)
        post :create, {:glucose_datum => {  }}, valid_session
        assigns(:glucose_datum).should be_a_new(GlucoseDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GlucoseDatum.any_instance.stub(:save).and_return(false)
        post :create, {:glucose_datum => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested glucose_datum" do
        glucose_datum = GlucoseDatum.create! valid_attributes
        # Assuming there are no other glucose_data in the database, this
        # specifies that the GlucoseDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GlucoseDatum.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => glucose_datum.to_param, :glucose_datum => { "these" => "params" }}, valid_session
      end

      it "assigns the requested glucose_datum as @glucose_datum" do
        glucose_datum = GlucoseDatum.create! valid_attributes
        put :update, {:id => glucose_datum.to_param, :glucose_datum => valid_attributes}, valid_session
        assigns(:glucose_datum).should eq(glucose_datum)
      end

      it "redirects to the glucose_datum" do
        glucose_datum = GlucoseDatum.create! valid_attributes
        put :update, {:id => glucose_datum.to_param, :glucose_datum => valid_attributes}, valid_session
        response.should redirect_to(glucose_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the glucose_datum as @glucose_datum" do
        glucose_datum = GlucoseDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GlucoseDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => glucose_datum.to_param, :glucose_datum => {  }}, valid_session
        assigns(:glucose_datum).should eq(glucose_datum)
      end

      it "re-renders the 'edit' template" do
        glucose_datum = GlucoseDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GlucoseDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => glucose_datum.to_param, :glucose_datum => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested glucose_datum" do
      glucose_datum = GlucoseDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => glucose_datum.to_param}, valid_session
      }.to change(GlucoseDatum, :count).by(-1)
    end

    it "redirects to the glucose_data list" do
      glucose_datum = GlucoseDatum.create! valid_attributes
      delete :destroy, {:id => glucose_datum.to_param}, valid_session
      response.should redirect_to(glucose_data_url)
    end
  end

end
